import type { ContentLocale } from "@/lib/i18n"

export const ticketCreateCopy = {
  tr: {
    title: "Yeni bilet",
    subtitle: "Sorununu detaylı anlat, ekibimiz en kısa sürede dönüş yapsın",
    help: "Yardım merkezi",
    formTitle: "Bilet bilgileri",
    formHint: "Zorunlu alanları doldur, ekleri ekle ve gönder",
    subject: "Konu",
    subjectHint: "Sorunu tek cümlede özetle",
    category: "Kategori",
    priority: "Öncelik",
    priorityHint: "Acil biletler sadece sistemin çalışmasını engelleyen sorunlar için",
    module: "İlgili modül",
    environment: "Etkilenen ortam",
    description: "Açıklama",
    descriptionHint: "Ne yapmaya çalışıyordun, ne oldu, ne bekliyordun?",
    markdown: "Markdown desteklenir",
    notify: "Yanıt gelince e-posta ile haber ver",
    cancel: "Vazgeç",
    saveDraft: "Taslak olarak kaydet",
    submit: "Bileti gönder",
    required: "*",
    pick: "Seçin",
    dropTitle: "Dosyaları sürükleyip bırak veya seç",
    dropHint: "PNG, JPG, PDF, LOG · en fazla 5 dosya · her biri 10 MB",
    dropErrorType: "Bu dosya türü kabul edilmiyor",
    dropErrorSize: "Dosya 10 MB sınırını aşıyor",
    dropErrorCount: "En fazla 5 dosya ekleyebilirsiniz",
    restoreDraft: "Kayıtlı bir taslak bulundu. Geri yüklemek ister misin?",
    restore: "Taslağı geri yükle",
    dismissDraft: "Yoksay",
    draftSaved: "Taslak kaydedildi",
    unsavedTitle: "Kaydedilmemiş değişiklikler var",
    unsavedBody: "Bu sayfadan ayrılırsan yazdıkların silinir.",
    stay: "Sayfada kal",
    leave: "Kaydetmeden çık",
    formError: "Göndermeden önce {n} alanı düzeltin",
    firstError: "İlk hataya git",
    subjectError: "Konu gerekli",
    categoryError: "Kategori seçin",
    priorityError: "Öncelik seçin",
    descriptionError: "Açıklama en az 30 karakter olmalı",
    submitted: "Biletin alındı",
    suggested: "Önerilen çözümler",
    suggestedHint: "Cevabı buldun mu? Bilet açmana gerek kalmayabilir.",
    previous: "Önceki biletlerim",
    viewAll: "Tümünü gör",
    hoursTitle: "Destek saatleri",
    hours: "Hafta içi 09:00–18:00",
    avgReply: "Ortalama ilk yanıt süresi: 2 saat",
    online: "Şu an çevrimiçiyiz",
    low: "Düşük",
    normal: "Normal",
    high: "Yüksek",
    urgent: "Acil",
  },
  en: {
    title: "New ticket",
    subtitle: "Describe the issue in detail so the team can reply quickly",
    help: "Help center",
    formTitle: "Ticket details",
    formHint: "Fill required fields, add files, then submit",
    subject: "Subject",
    subjectHint: "Summarize the issue in one sentence",
    category: "Category",
    priority: "Priority",
    priorityHint: "Use urgent only when the system is blocked",
    module: "Related module",
    environment: "Affected environment",
    description: "Description",
    descriptionHint: "What did you try, what happened, what did you expect?",
    markdown: "Markdown is supported",
    notify: "Email me when there is a reply",
    cancel: "Cancel",
    saveDraft: "Save as draft",
    submit: "Submit ticket",
    required: "*",
    pick: "Select",
    dropTitle: "Drag and drop files or browse",
    dropHint: "PNG, JPG, PDF, LOG · up to 5 files · 10 MB each",
    dropErrorType: "This file type is not allowed",
    dropErrorSize: "File exceeds the 10 MB limit",
    dropErrorCount: "You can attach up to 5 files",
    restoreDraft: "A saved draft was found. Restore it?",
    restore: "Restore draft",
    dismissDraft: "Dismiss",
    draftSaved: "Draft saved",
    unsavedTitle: "You have unsaved changes",
    unsavedBody: "If you leave this page your text will be lost.",
    stay: "Stay on page",
    leave: "Leave without saving",
    formError: "Fix {n} fields before submitting",
    firstError: "Go to first error",
    subjectError: "Subject is required",
    categoryError: "Choose a category",
    priorityError: "Choose a priority",
    descriptionError: "Description must be at least 30 characters",
    submitted: "Ticket received",
    suggested: "Suggested articles",
    suggestedHint: "Found an answer? You may not need a ticket.",
    previous: "My previous tickets",
    viewAll: "View all",
    hoursTitle: "Support hours",
    hours: "Weekdays 09:00–18:00",
    avgReply: "Average first reply: 2 hours",
    online: "We are online now",
    low: "Low",
    normal: "Normal",
    high: "High",
    urgent: "Urgent",
  },
} as const

export function createCopy(locale: ContentLocale) {
  return ticketCreateCopy[locale]
}
