import type { ContentLocale } from "@/lib/i18n"

export type DashboardLocale = ContentLocale

export type ProjectPriority = "low" | "medium" | "high" | "veryHigh"

export const dashboardCopy = {
  tr: {
    pageTitle: "Ana Sayfa",
    last30Days: "Son 30 gün",
    filter: "Filtrele",
    download: "Rapor indir",
    kpis: ["Lorem ipsum", "Dolor sit", "Amet elit", "Sed do", "Eiusmod", "Tempor"],
    revenueTitle: "Incididunt ut labore",
    revenueHint: "Et dolore magna",
    totalEarnings: "Aliqua enim ad",
    earningsMonth: "Minim veniam quis",
    expenseMonth: "Nostrud exercitation",
    viewReport: "Ullamco laboris",
    yearlyTitle: "Nisi ut aliquip",
    lastYear: "Ex ea commodo",
    thisYear: "Consequat duis",
    prevYear: "Aute irure dolor",
    monthlyTitle: "In reprehenderit",
    salaryTitle: "Voluptate velit",
    salaryHint: "Esse cillum dolore",
    salary: "Eu fugiat nulla",
    profit: "Pariatur excepteur",
    customers: "Sint occaecat",
    projects: "Cupidatat non",
    promoTitle: "Proident sunt in culpa",
    promoHint: "Qui officia deserunt mollit anim",
    promoDate: "22 March, 2025",
    bestTitle: "Id est laborum",
    bestHint: "Sed ut perspiciatis",
    weeklyTitle: "Unde omnis iste",
    weeklyHint: "Natus error sit",
    tableTitle: "Voluptatem accusantium",
    tableHint: "Doloremque laudantium",
    assigned: "Totam rem",
    project: "Aperiam eaque",
    priority: "Ipsa quae",
    budget: "Ab illo",
    year: "2025",
    welcomeUser: "Lorem Ipsum",
    welcomeHint:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.",
    welcomeCta: "Ut enim ad minim",
    greetingMorning: "Günaydın",
    greetingAfternoon: "İyi günler",
    greetingEvening: "İyi akşamlar",
    greetingNight: "İyi geceler",
    visitTitle: "Quis nostrud",
    visitTotalLabel: "exercitation ullamco",
  },
  en: {
    pageTitle: "Home",
    last30Days: "Last 30 days",
    filter: "Filter",
    download: "Download report",
    kpis: ["Lorem ipsum", "Dolor sit", "Amet elit", "Sed do", "Eiusmod", "Tempor"],
    revenueTitle: "Incididunt ut labore",
    revenueHint: "Et dolore magna",
    totalEarnings: "Aliqua enim ad",
    earningsMonth: "Minim veniam quis",
    expenseMonth: "Nostrud exercitation",
    viewReport: "Ullamco laboris",
    yearlyTitle: "Nisi ut aliquip",
    lastYear: "Ex ea commodo",
    thisYear: "Consequat duis",
    prevYear: "Aute irure dolor",
    monthlyTitle: "In reprehenderit",
    salaryTitle: "Voluptate velit",
    salaryHint: "Esse cillum dolore",
    salary: "Eu fugiat nulla",
    profit: "Pariatur excepteur",
    customers: "Sint occaecat",
    projects: "Cupidatat non",
    promoTitle: "Proident sunt in culpa",
    promoHint: "Qui officia deserunt mollit anim",
    promoDate: "22 March, 2025",
    bestTitle: "Id est laborum",
    bestHint: "Sed ut perspiciatis",
    weeklyTitle: "Unde omnis iste",
    weeklyHint: "Natus error sit",
    tableTitle: "Voluptatem accusantium",
    tableHint: "Doloremque laudantium",
    assigned: "Totam rem",
    project: "Aperiam eaque",
    priority: "Ipsa quae",
    budget: "Ab illo",
    year: "2025",
    welcomeUser: "Lorem Ipsum",
    welcomeHint:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.",
    welcomeCta: "Ut enim ad minim",
    greetingMorning: "Good morning",
    greetingAfternoon: "Good afternoon",
    greetingEvening: "Good evening",
    greetingNight: "Good night",
    visitTitle: "Quis nostrud",
    visitTotalLabel: "exercitation ullamco",
  },
} as const

export const dashboardPriorityLabels: Record<
  ProjectPriority,
  Record<DashboardLocale, string>
> = {
  low: { tr: "Lorem", en: "Lorem" },
  medium: { tr: "Ipsum", en: "Ipsum" },
  high: { tr: "Dolor", en: "Dolor" },
  veryHigh: { tr: "Sit amet", en: "Sit amet" },
}
