import type { ContentLocale } from "@/lib/i18n"

export type BlogEditorMode = "create" | "edit"

export const blogEditorCopy = {
  tr: {
    createTitle: "Yeni blog yazısı",
    editTitle: "Yazıyı düzenle",
    cancel: "Vazgeç",
    saveDraft: "Taslak olarak kaydet",
    publish: "Yayınla",
    autosave: "Taslak otomatik kaydedilecek",
    missing: "zorunlu alan eksik",
    step: "Adım",
    steps: [
      { title: "Temel bilgiler", hint: "Yazının başlığı, adresi ve özet bilgileri" },
      { title: "İçerik", hint: "Yazı gövdesi ve zengin metin içeriği" },
      { title: "Görsel ve sınıflandırma", hint: "Kapak görseli, kategori ve etiket atamaları" },
      { title: "Yayın ve SEO", hint: "Yayınlanma zamanı, görünürlük ve arama motoru optimizasyonu" },
    ] as const,
    done: "Tamamlandı",
    inProgress: "Devam ediyor",
    title: "Başlık",
    titleHint: "Arama sonuçlarında görünecek ana başlık",
    slug: "Kalıcı bağlantı (slug)",
    slugPrefix: "site.com/blog/",
    slugHint: "Başlıktan otomatik üretilir, istersen düzenle",
    excerpt: "Kısa özet",
    excerptHint: "Liste ve kartlarda görünür",
    excerptPlaceholder: "Yazının 1-2 cümlelik özeti",
    author: "Yazar",
    readTime: "Okuma süresi",
    autoRead: "Otomatik hesapla",
    minutes: "dk",
    required: "*",
    body: "Yazı içeriği",
    bodyPlaceholder: "Yazını buraya yaz…",
    bodyHint: "En az 300 kelime önerilir",
    words: "kelime",
    paragraph: "Paragraf",
    cover: "Kapak görseli",
    coverTitle: "Görseli sürükleyip bırak veya dosya seç",
    coverHint: "PNG, JPG veya WebP · 1200 × 630 px önerilir · en fazla 2 MB",
    pickFile: "Dosya seç",
    alt: "Alt metin (Görsel açıklaması)",
    altPlaceholder: "Görsel yüklendiğinde aktif olur",
    category: "Kategori",
    categoryPick: "Kategori seç",
    newCategory: "Yeni kategori",
    series: "Seri / koleksiyon",
    seriesOptional: "İsteğe bağlı",
    seriesNone: "Seçilmedi",
    tags: "Etiketler",
    tagsPlaceholder: "Etiket ekle ve Enter’a bas",
    suggested: "Önerilenler",
    status: "Durum",
    draft: "Taslak",
    published: "Yayında",
    scheduled: "Zamanlanmış",
    visibility: "Görünürlük",
    visPublic: "Herkese açık",
    visPublicHint: "Tüm ziyaretçiler ve arama motorları görebilir",
    visHidden: "Gizli",
    visHiddenHint: "Yalnızca doğrudan bağlantıya sahip olanlar",
    visLocked: "Şifreli",
    visLockedHint: "Görüntülemek için parola gereklidir",
    comments: "Yorumlara izin ver",
    commentsHint: "Okuyucular bu yazıya yorum bırakabilir",
    featured: "Öne çıkan yazı",
    featuredHint: "Blog ana sayfasının en üstünde sabitlenir",
    seo: "Arama motoru (SEO)",
    metaTitle: "Meta başlık",
    metaDesc: "Meta açıklama",
    metaDescPlaceholder: "Arama motoru sonucu için açıklama girin…",
    googlePreview: "Google önizlemesi",
    seoScore: "SEO uyumluluğu",
    seoTitleOk: "Başlık uzunluğu uygun",
    seoDescMissing: "Meta açıklama eksik",
    previewHost: "site.com › blog",
    previewEmpty: "Arama motorunda henüz açıklama bulunmuyor.",
  },
  en: {
    createTitle: "New blog post",
    editTitle: "Edit post",
    cancel: "Cancel",
    saveDraft: "Save draft",
    publish: "Publish",
    autosave: "Draft will be saved automatically",
    missing: "required fields missing",
    step: "Step",
    steps: [
      { title: "Basics", hint: "Title, slug, and summary" },
      { title: "Content", hint: "Post body and rich text" },
      { title: "Media and taxonomy", hint: "Cover, category, and tags" },
      { title: "Publish and SEO", hint: "Schedule, visibility, and search" },
    ] as const,
    done: "Done",
    inProgress: "In progress",
    title: "Title",
    titleHint: "Main title shown in search results",
    slug: "Permalink (slug)",
    slugPrefix: "site.com/blog/",
    slugHint: "Generated from the title; you can edit it",
    excerpt: "Short excerpt",
    excerptHint: "Shown on lists and cards",
    excerptPlaceholder: "One or two sentences",
    author: "Author",
    readTime: "Read time",
    autoRead: "Auto calculate",
    minutes: "min",
    required: "*",
    body: "Post content",
    bodyPlaceholder: "Write your post here…",
    bodyHint: "At least 300 words is recommended",
    words: "words",
    paragraph: "Paragraph",
    cover: "Cover image",
    coverTitle: "Drop an image or choose a file",
    coverHint: "PNG, JPG, or WebP · 1200 × 630 px · max 2 MB",
    pickFile: "Choose file",
    alt: "Alt text",
    altPlaceholder: "Enabled after an image is uploaded",
    category: "Category",
    categoryPick: "Choose a category",
    newCategory: "New category",
    series: "Series / collection",
    seriesOptional: "Optional",
    seriesNone: "Not selected",
    tags: "Tags",
    tagsPlaceholder: "Add a tag and press Enter",
    suggested: "Suggested",
    status: "Status",
    draft: "Draft",
    published: "Published",
    scheduled: "Scheduled",
    visibility: "Visibility",
    visPublic: "Public",
    visPublicHint: "Visible to visitors and search engines",
    visHidden: "Hidden",
    visHiddenHint: "Only people with the direct link",
    visLocked: "Password",
    visLockedHint: "A password is required to view",
    comments: "Allow comments",
    commentsHint: "Readers can comment on this post",
    featured: "Featured post",
    featuredHint: "Pinned at the top of the blog home",
    seo: "Search engine (SEO)",
    metaTitle: "Meta title",
    metaDesc: "Meta description",
    metaDescPlaceholder: "Description for search results…",
    googlePreview: "Google preview",
    seoScore: "SEO score",
    seoTitleOk: "Title length is fine",
    seoDescMissing: "Meta description is missing",
    previewHost: "site.com › blog",
    previewEmpty: "No search description yet.",
  },
} as const

export const blogAuthors = ["Yakup K. (Yönetici)", "Ahmet Y. (Yazar)", "Zeynep B. (Editör)"] as const
export const blogSeries = ["Frontend Mimari Serisi", "Tasarım Sistemleri Rehberi"] as const
export const blogSuggestedTags = ["react", "mimari", "tailwind"] as const
