import type { ContentLocale } from "@/lib/i18n"

export const loginCopy = {
  tr: {
    panelKicker: "Lorem ipsum",
    version: "v1.0",
    headlineLead: "Lorem ipsum dolor sit",
    headlineAccent: "amet consectetur.",
    headlineMobile: "Lorem ipsum dolor sit amet consectetur.",
    panelBody:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    features: [
      "Ut enim ad minim veniam",
      "Quis nostrud exercitation",
      "Duis aute irure dolor",
    ] as const,
    title: "Tekrar hoş geldin",
    subtitle: "Hesabına giriş yap ve kaldığın yerden devam et.",
    username: "Kullanıcı adı",
    usernamePlaceholder: "admin",
    password: "Şifre",
    passwordPlaceholder: "password",
    forgot: "Şifremi unuttum",
    remember: "Beni hatırla",
    submit: "Giriş yap",
    submitting: "Giriş yapılıyor…",
    or: "veya",
    google: "Google ile devam et",
    microsoft: "Microsoft ile devam et",
    soon: "Yakında",
    noAccount: "Hesabın yok mu?",
    register: "Kayıt ol",
    privacy: "Gizlilik",
    terms: "Kullanım koşulları",
    support: "Destek",
    encryption: "256-bit şifreleme ile korunuyor",
    showPassword: "Şifreyi göster",
    hidePassword: "Şifreyi gizle",
    language: "Dil",
    theme: "Tema",
  },
  en: {
    panelKicker: "Lorem ipsum",
    version: "v1.0",
    headlineLead: "Lorem ipsum dolor sit",
    headlineAccent: "amet consectetur.",
    headlineMobile: "Lorem ipsum dolor sit amet consectetur.",
    panelBody:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    features: [
      "Ut enim ad minim veniam",
      "Quis nostrud exercitation",
      "Duis aute irure dolor",
    ] as const,
    title: "Welcome back",
    subtitle: "Sign in and pick up where you left off.",
    username: "Username",
    usernamePlaceholder: "admin",
    password: "Password",
    passwordPlaceholder: "password",
    forgot: "Forgot password",
    remember: "Remember me",
    submit: "Sign in",
    submitting: "Signing in…",
    or: "or",
    google: "Continue with Google",
    microsoft: "Continue with Microsoft",
    soon: "Coming soon",
    noAccount: "Don’t have an account?",
    register: "Sign up",
    privacy: "Privacy",
    terms: "Terms",
    support: "Support",
    encryption: "Protected with 256-bit encryption",
    showPassword: "Show password",
    hidePassword: "Hide password",
    language: "Language",
    theme: "Theme",
  },
} as const

export function getLoginCopy(locale: ContentLocale) {
  return loginCopy[locale]
}
