import type { ContentLocale } from "@/lib/i18n"

export type ProfileLocale = ContentLocale

export const profileCopy = {
  tr: {
    profile: "Profil",
    followers: "Takipçiler",
    friends: "Arkadaşlar",
    gallery: "Galeri",
    following: "Takip",
    about: "Hakkında",
    aboutText:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    liveAt: "Lorem ipsum",
    country: "dolor sit",
    role: "Lorem ipsum",
    company: "consectetur adipiscing",
    school: "elit sed do",
    studied: "Lorem",
    social: "Sosyal",
    placeholder: "Ne düşündüğünü burada paylaş...",
    image: "Görsel",
    stream: "Yayın",
    post: "Paylaş",
    comment: "Yorum yaz...",
    more: "Diğer",
    commentAction: "Yorum",
    share: "Paylaş",
  },
  en: {
    profile: "Profile",
    followers: "Followers",
    friends: "Friends",
    gallery: "Gallery",
    following: "Following",
    about: "About",
    aboutText:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    liveAt: "Lorem ipsum",
    country: "dolor sit",
    role: "Lorem ipsum",
    company: "consectetur adipiscing",
    school: "elit sed do",
    studied: "Lorem",
    social: "Social",
    placeholder: "Share what you are thinking here...",
    image: "Image",
    stream: "Streaming",
    post: "Post",
    comment: "Write a comment...",
    more: "More",
    commentAction: "Comment",
    share: "Share",
  },
} as const
