import type { ContentLocale } from "@/lib/i18n"

export const ticketsCopy = {
  tr: {
    title: "Biletler",
    excel: "Excel",
    reports: "Raporlar",
    soon: "Yakında",
    all: "Tümü",
    open: "Açık",
    inReview: "İnceleniyor",
    resolved: "Çözüldü",
    closed: "Kapalı",
    avgReply: "Ort. ilk yanıt 1s 42dk",
    slaBreach: "SLA ihlali",
    search: "Talep no, konu veya kullanıcı",
    priority: "Öncelik",
    category: "Kategori",
    assignee: "Atanan kişi",
    date: "Tarih",
    sort: "Sırala",
    clear: "Filtreleri temizle",
    filters: "Filtreler",
    today: "Bugün",
    days7: "Son 7 gün",
    days30: "Son 30 gün",
    newest: "En yeni",
    oldest: "En eski",
    byPriority: "Önceliğe göre",
    bySla: "SLA'ya göre",
    unassigned: "Atanmamış",
    ticketsCount: "bilet",
    empty: "Bu filtreyle bilet bulunamadı",
    selectAll: "Tümünü seç",
    selected: "seçili",
    assign: "Ata",
    changeStatus: "Durumu değiştir",
    close: "Kapat",
    copyLink: "Bağlantıyı kopyala",
    copied: "Bağlantı kopyalandı",
    print: "Yazdır",
    merge: "Birleştir",
    delete: "Sil",
    requester: "Talep eden",
    created: "Oluşturulma",
    sla: "SLA",
    tags: "Etiketler",
    reply: "Yanıt",
    internal: "Dahili not",
    internalHint: "Dahili not · sadece ekip görür",
    canned: "Hazır yanıt",
    markReview: "Gönderince durumu 'İnceleniyor' yap",
    saveDraft: "Taslağı kaydet",
    send: "Gönder",
    closeTicket: "Talebi kapat",
    closeConfirmTitle: "Talebi kapat",
    closeConfirm: "Bu bilet kapatılacak. Emin misin?",
    emptyDetail: "Detayları görmek için bir bilet seç",
    assignTitle: "Bileti ata",
    cancel: "Vazgeç",
    openTickets: "açık bilet",
    back: "Geri",
    module: "Modül",
    low: "Düşük",
    normal: "Normal",
    high: "Yüksek",
    urgent: "Acil",
    updated: "Güncellendi",
    canned1Title: "Bilgi aldık",
    canned1: "Talebini aldık, inceliyoruz. Kısa sürede dönüş yapacağız.",
    canned2Title: "Daha fazla bilgi",
    canned2: "Sorunu tekrarlayabilmemiz için tarayıcı ve saat bilgisini yazar mısın?",
    canned3Title: "Çözüldü",
    canned3: "Düzeltmeyi yayınladık. Hâlâ sorun varsa yanıtla lütfen.",
  },
  en: {
    title: "Tickets",
    excel: "Excel",
    reports: "Reports",
    soon: "Coming soon",
    all: "All",
    open: "Open",
    inReview: "In review",
    resolved: "Resolved",
    closed: "Closed",
    avgReply: "Avg. first reply 1h 42m",
    slaBreach: "SLA breach",
    search: "Ticket no, subject or user",
    priority: "Priority",
    category: "Category",
    assignee: "Assignee",
    date: "Date",
    sort: "Sort",
    clear: "Clear filters",
    filters: "Filters",
    today: "Today",
    days7: "Last 7 days",
    days30: "Last 30 days",
    newest: "Newest",
    oldest: "Oldest",
    byPriority: "By priority",
    bySla: "By SLA",
    unassigned: "Unassigned",
    ticketsCount: "tickets",
    empty: "No tickets match these filters",
    selectAll: "Select all",
    selected: "selected",
    assign: "Assign",
    changeStatus: "Change status",
    close: "Close",
    copyLink: "Copy link",
    copied: "Link copied",
    print: "Print",
    merge: "Merge",
    delete: "Delete",
    requester: "Requester",
    created: "Created",
    sla: "SLA",
    tags: "Tags",
    reply: "Reply",
    internal: "Internal note",
    internalHint: "Internal note · team only",
    canned: "Canned reply",
    markReview: "Set status to In review after send",
    saveDraft: "Save draft",
    send: "Send",
    closeTicket: "Close ticket",
    closeConfirmTitle: "Close ticket",
    closeConfirm: "This ticket will be closed. Continue?",
    emptyDetail: "Select a ticket to see details",
    assignTitle: "Assign ticket",
    cancel: "Cancel",
    openTickets: "open tickets",
    back: "Back",
    module: "Module",
    low: "Low",
    normal: "Normal",
    high: "High",
    urgent: "Urgent",
    updated: "Updated",
    canned1Title: "We received it",
    canned1: "We received your request and are reviewing it. We will reply shortly.",
    canned2Title: "Need more detail",
    canned2: "Please share browser and time so we can reproduce the issue.",
    canned3Title: "Resolved",
    canned3: "The fix is live. Reply if you still see the issue.",
  },
} as const

export function inboxCopy(locale: ContentLocale) {
  return ticketsCopy[locale]
}
