import type { Metadata } from "next";
import { Geist_Mono, Inter, Nunito, Outfit, Source_Sans_3 } from "next/font/google";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Toaster } from "@/components/toast/toaster";
import { DEFAULT_THEME_ACCENT } from "@/lib/theme/accents";
import { DEFAULT_FONT_FAMILY, DEFAULT_FONT_SIZE } from "@/lib/theme/fonts";
import "./globals.css";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin", "latin-ext"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "latin-ext"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const sourceSans = Source_Sans_3({
  variable: "--font-source",
  subsets: ["latin", "latin-ext"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by next-template",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-accent={DEFAULT_THEME_ACCENT}
      data-density="comfortable"
      data-layout="side"
      data-footer="on"
      data-font={DEFAULT_FONT_FAMILY}
      data-font-size={DEFAULT_FONT_SIZE}
      className={`${nunito.variable} ${inter.variable} ${outfit.variable} ${sourceSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="flex h-dvh flex-col overflow-hidden">
        <ThemeProvider>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
